### ISSUE TITLE
Metalsmith CLI is broken (1.4.0 & 1.4.1)

### ISSUE THREAD

**Issue by michaelgilley** [segmentio/metalsmith#127]
```$ node_modules/.bin/metalsmith```

Metalsmith · undefined is not a function

I'm using ZSH if that makes a difference.

**Comment by christophercliff** [comment]
+1

**Comment by ianstormtaylor** [comment]
Shoot. Do you guys have a stack track? Seeing a similar thing that looks like it's coming from `metalsmith-templates`, but weird. Investigating now.

**Comment by thatluke** [comment]
Here you go, Ian,

Metalsmith · undefined is not a function

TypeError: undefined is not a function

    at Metalsmith.callee$0$3$
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/lib/index.js:279:12)

    at tryCatch
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/gnode/node_modules/regenerator/runtime.js:53:40)

    at GeneratorFunctionPrototype.invoke
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/gnode/node_modules/regenerator/runtime.js:209:22)

    at next
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:74:21)

    at Metalsmith.<anonymous>
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:45:5)

    at run
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:194:12)

    at Metalsmith.<anonymous>
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:181:7)

    at Metalsmith.next
(/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:90:21)

    at
/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:93:18

    at
/Users/luke/Sites/Github/casalasgemelas/node_modules/metalsmith/node_modules/thunkify/index.js:39:14

    at ChildProcess.exithandler (child_process.js:658:15)

    at ChildProcess.emit (events.js:98:17)

    at maybeClose (child_process.js:766:16)

    at Socket.<anonymous> (child_process.js:979:11)

    at Socket.emit (events.js:95:17)

    at Pipe.close (net.js:466:12)


Warmest Regards,


Luke Gschwend

C. 310-622-5701

**Comment by madevelopers** [comment]
I have the same problem. I used node v0.10.32. I updated to v0.12.1 and it worked.

**Comment by redism** [comment]
Doesn't seem to work on v0.10.x, but works with v0.12.x.
metalsmith version used is 1.4.1, gitHead : 0122ddfab30f9f3d85579b8ecef187a70ccd7c44

```
[-:master] redism@~/dev/redism.github.io: node --version
v0.10.38
[-:master] redism@~/dev/redism.github.io: cat index.js
var Metalsmith = require('metalsmith');

Metalsmith(__dirname)
  .build(function(err) {
    if (err) throw err;
  });
[-:master] redism@~/dev/redism.github.io: node index.js

/Users/redism/dev/redism.github.io/index.js:5
    if (err) throw err;
                   ^
TypeError: undefined is not a function
    at Metalsmith.callee$0$3$ (/Users/redism/dev/redism.github.io/node_modules/metalsmith/lib/index.js:279:12)
    at tryCatch (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/gnode/node_modules/regenerator/runtime.js:53:40)
    at GeneratorFunctionPrototype.invoke (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/gnode/node_modules/regenerator/runtime.js:209:22)
    at next (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:74:21)
    at Metalsmith.<anonymous> (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:45:5)
    at run (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:194:12)
    at Metalsmith.<anonymous> (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:181:7)
    at Metalsmith.next (/Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:90:21)
    at /Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:93:18
    at /Users/redism/dev/redism.github.io/node_modules/metalsmith/node_modules/thunkify/index.js:39:14
[-:master] redism@~/dev/redism.github.io:
[-:master] redism@~/dev/redism.github.io: nvm use 0.12
Now using node v0.12.1
[-:master] redism@~/dev/redism.github.io: node index.js
[-:master] redism@~/dev/redism.github.io:
```

**Comment by ianstormtaylor** [comment]
cc @matthewmueller you ever see anything like this? Only working on `0.12` makes me think it has something to do with `unyield`?

**Comment by Kerry350** [comment]
I was getting the same error, with the same stacktrace, when I went debugging it looked like it was because of `isAbsolute` being used, and `path.isAbsolute` not being in Node.js `0.10.36`.

**Comment by ianstormtaylor** [comment]
Doh, fix incoming! Thanks so much @Kerry350

**Comment by ianstormtaylor** [comment]
Fixed in `1.4.4`, let me know if anyone still has any issues! Sorry for delay
